{"uuid": "0a79cdfa-e502-4f1e-829f-f751b017ac2d", "children": ["4e96aa23-dcb1-4190-bdfc-91ca27d9765a"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: no such execution context\n  (Session info: chrome=123.0.6312.122)\nStacktrace:\n\tGetHandleVerifier [0x00007FF71AF97032+63090]\n\t(No symbol) [0x00007FF71AF02C82]\n\t(No symbol) [0x00007FF71AD9EB1D]\n\t(No symbol) [0x00007FF71AD8C76D]\n\t(No symbol) [0x00007FF71AD8B100]\n\t(No symbol) [0x00007FF71AD8BA8F]\n\t(No symbol) [0x00007FF71AD9925A]\n\t(No symbol) [0x00007FF71ADAAB0E]\n\t(No symbol) [0x00007FF71ADAF82A]\n\t(No symbol) [0x00007FF71AD8C006]\n\t(No symbol) [0x00007FF71ADAA6A4]\n\t(No symbol) [0x00007FF71AE232ED]\n\t(No symbol) [0x00007FF71AE06D83]\n\t(No symbol) [0x00007FF71ADD83A8]\n\t(No symbol) [0x00007FF71ADD9441]\n\tGetHandleVerifier [0x00007FF71B3925AD+4238317]\n\tGetHandleVerifier [0x00007FF71B3CF70D+4488525]\n\tGetHandleVerifier [0x00007FF71B3C79EF+4456495]\n\tGetHandleVerifier [0x00007FF71B070576+953270]\n\t(No symbol) [0x00007FF71AF0E54F]\n\t(No symbol) [0x00007FF71AF09224]\n\t(No symbol) [0x00007FF71AF0935B]\n\t(No symbol) [0x00007FF71AEF9B94]\n\tBaseThreadInitThunk [0x00007FFA507A257D+29]\n\tRtlUserThreadStart [0x00007FFA5134AA58+40]\n\n", "trace": "  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nik54\\PycharmProjects\\Automationproject123\\test\\conftest.py\", line 29, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\nik54\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1713458293434, "stop": 1713458295283}], "start": 1713458293434, "stop": 1713458295512}